cargo-features = ["edition2024"]

[package]
name = "lab_pbr_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive", "cargo", "string"] }
image = { version = "0.25", default-features = false, features = [
	"rayon",
	"png",
] }
