# See https://github.com/bevyengine/bevy/blob/latest/.cargo/config_fast_builds.toml for installation instructions

[target.x86_64-unknown-linux-gnu]
# Mold linker
#
# You may need to install it:
#
# - Ubuntu: `sudo apt-get install mold clang`
# - Fedora: `sudo dnf install mold clang`
# - Arch: `sudo pacman -S mold clang`
linker = "clang"
rustflags = [
	"-Clink-arg=-fuse-ld=/usr/bin/mold",
	"-Zshare-generics=y",
	"-Zthreads=0",
]

[target.x86_64-apple-darwin]
rustflags = ["-Zshare-generics=y", "-Zthreads=0"]

[target.aarch64-apple-darwin]
rustflags = ["-Zshare-generics=y", "-Zthreads=0"]

[target.x86_64-pc-windows-msvc]
# LLD linker
#
# You may need to install it:
#
# ```
# cargo install -f cargo-binutils
# rustup component add llvm-tools
# ```
linker = "rust-lld.exe"

[alias]
ci = "run --package ci --"
